Migrate study server to postgressql [WIP]
gridsuite/deployment pull request #111
Opened 2021-02-16 14:25 UTC by ChamseddineBhd

2021-02-17 12:22 UTC, FranckLecuyer requested changes

2021-02-17 12:22 UTC, FranckLecuyer commented on k8s/base/config/study-server-application.yml
> +  cloud:
'cloud' part is already in the study-server application.yaml file ...

2021-02-18 09:00 UTC, AbdelHedhili approved these changes

2021-02-19 08:47 UTC, FranckLecuyer approved these changes

2021-03-24 12:11 UTC, merged