renaming griddata to gridaction
gridsuite/deployment pull request #134
Opened 2021-04-19 15:16 UTC by JacquesBorsenberger

2021-04-27 13:44 UTC, FranckLecuyer requested changes
You have to rename gridactions to griddata in .github/workflows/main.yml file also

2021-04-28 10:56 UTC, FranckLecuyer approved these changes

2021-05-06 14:42 UTC, ChamseddineBhd approved these changes

2021-05-06 14:42 UTC, ChamseddineBhd commented on docker-compose/actions/docker-compose.override.yml
> +    image: gridsuite/griddata-app:latest
do not forget to deploy the new the docker image before merging this PR

2021-07-22 12:13 UTC, closed without merging