US 705 migration to postgres+liquibase, adds postgres database 'sa'
gridsuite/deployment pull request #216
Opened 2022-02-10 09:57 UTC by laurgarn

2022-02-10 15:00 UTC, sBouzols approved these changes
Code Review ok for me
Test :
* [x] Docker-compose deployment

2022-02-10 15:06 UTC, SlimaneAmar requested changes

2022-02-10 15:06 UTC, SlimaneAmar commented on README.md
> +$ create database sa;
Remove CREATE KEYSPACE for SA

2022-02-10 17:49 UTC, laurgarn commented on README.md
> +$ create database sa;
Done

2022-02-11 07:13 UTC, SlimaneAmar approved these changes

2022-02-11 08:10 UTC, merged