Switching to postgres of assembling job
gridsuite/deployment pull request #227
Opened 2022-04-15 09:10 UTC by YenguiSeddik

2022-04-15 09:22 UTC, sBouzols requested changes

2022-04-15 09:22 UTC, sBouzols commented on docker-compose/technical/create-cassandra-databases.sh
>  until cqlsh -f /create_keyspaces.cql; do
this file `create_keyspaces.cql` is now empty...

2022-04-15 09:22 UTC, sBouzols commented on docker-compose/technical/create-cassandra-databases.sh
>    sleep 2
init_keyspaces.cql doesn't exist anymore.
Ok then remove everything in this file except the last command
`exec /docker-entrypoint.sh "$@"`

2022-04-15 09:23 UTC, sBouzols requested changes
must edit docker-compose/merging/cgmes-assembling-job/cgmes-assembling-job-config.yml
as well

2022-04-15 11:26 UTC, sBouzols requested changes

2022-04-15 11:26 UTC, sBouzols commented on docker-compose/merging/cgmes-assembling-job/cgmes-assembling-job-config.yml
> +  url: jdbc:postgresql://localhost:5432/cgmes_assembling
`172.17.0.1` instead of `localhost` to be the same as in docker-compose/merging/case-import-job/case-import-job-config.yml

2022-04-15 11:27 UTC, sBouzols approved these changes

2022-04-21 09:55 UTC, jonenst approved these changes

2022-04-21 09:57 UTC, merged