[WIP] Default values for gridstudy parameters depending on environment
gridsuite/deployment pull request #230
Opened 2022-04-25 11:41 UTC by archendel

Signed-off-by: LE SAULNIER Kevin <kevin.lesaulnier@rte-france.com>

2022-05-02 07:44 UTC, FranckLecuyer requested changes

2022-05-02 07:44 UTC, FranckLecuyer commented on k8s/base/config/common-application.yml
> +  default-provider: OpenLoadFlow
Why defined here, and not in loadflow-server-application.yml ?
And maybe, we should keep loadflow-server-application.yml file, if we need to add specific properties in the future ...

2022-05-04 08:47 UTC, FranckLecuyer approved these changes

2022-05-04 09:02 UTC, jonenst approved these changes

2022-05-04 11:11 UTC, merged