update readme due to the modifiacation in odre-server endpoints
gridsuite/deployment pull request #253
Opened 2022-08-26 12:14 UTC by bendaamerahm

2022-08-30 09:35 UTC, sBouzols requested changes

2022-08-30 09:35 UTC, sBouzols commented on README.md
> +* .../substations/
typo
remove the last '/'

2022-08-30 09:52 UTC, bendaamerahm commented on README.md
> +* .../substations/
nice catch

2022-09-01 14:01 UTC, sBouzols approved these changes

2022-09-09 07:59 UTC, merged