Split
gridsuite/deployment pull request #265
Opened 2022-09-14 14:01 UTC by jonenst

2022-09-14 15:35 UTC, bendaamerahm requested changes

2022-09-14 15:35 UTC, bendaamerahm commented on README.md
> +$ sed -i -e "s/<INGRESS_HOST>/${INGRESS_HOST}/g" k8s/live/local/*
dosent work cause there's a sub dir patches, maby we change it by using this cmd : 
`$ find k8s/live/local -type f -exec sed -i -e "s/<INGRESS_HOST>/${INGRESS_HOST}/g" {} \;`

2022-09-14 15:35 UTC, bendaamerahm commented on README.md
> +$ sed -i -e 's/<PASSWORD>/YOURPASSWORD/g' k8s/live/local/*
same

2022-09-14 15:35 UTC, bendaamerahm commented on README.md
> +$ kubectl apply -k k8s/live/local
same

2022-09-15 07:50 UTC, jonenst commented on README.md
> +$ sed -i -e 's/<PASSWORD>/YOURPASSWORD/g' k8s/live/local/*
done

2022-09-15 08:01 UTC, bendaamerahm approved these changes

2022-09-15 08:40 UTC, sBouzols approved these changes

2022-09-15 08:51 UTC, merged