add case-import-server deployment
gridsuite/deployment pull request #325
Opened 2023-06-27 09:06 UTC by AbdelHedhili

2023-08-23 08:47 UTC, FranckLecuyer requested changes
Missing case-import-server in main.yml file
Missing case-import-server in README.md

2023-08-23 08:47 UTC, FranckLecuyer commented on k8s/resources/study/kustomization.yaml
> +  - name: voltage-init-server-itools-configmap
duplicated

2023-08-23 12:40 UTC, etiennehomer commented
Maybe add an empty case-import-server-application.yml to be homogeneous with the other services

2023-08-25 07:13 UTC, AbdelHedhili commented
> Maybe add an empty case-import-server-application.yml to be homogeneous with the other services

We don't seem to have these empty files for all the servers, I'm not even sure why they exist, but I added it

2023-08-25 07:18 UTC, AbdelHedhili commented on k8s/resources/study/kustomization.yaml
> +  - name: voltage-init-server-itools-configmap
fixed

2023-08-25 08:48 UTC, FranckLecuyer approved these changes

2023-08-25 13:08 UTC, etiennehomer approved these changes

2023-08-25 13:18 UTC, merged