Migrate dasboards to grafana 10 2
gridsuite/deployment pull request #383
Opened 2024-02-06 15:32 UTC by SlimaneAmar

2024-02-07 17:01 UTC, antoinebhs commented on docker-compose/technical/docker-compose.technical.yml
> +    image: grafana/grafana:10.2.2
No update of prometheus?

2024-02-07 17:06 UTC, SlimaneAmar commented on docker-compose/technical/docker-compose.technical.yml
> +    image: grafana/grafana:10.2.2
Jimmy said it was the same version

2024-02-07 17:17 UTC, antoinebhs requested changes
* On devopf, there is no data for security analysis in the **Computations** dashboard
* Should remove the "Network load time" as it's not meaningful in the **Computations** dashboard
* Need to handle multiple pods in the **Computations** dashboard (and maybe network-conversion?), it gets messy otherwise: 
![image](https://github.com/gridsuite/deployment/assets/123802855/b3ca93c7-9840-48ce-ad50-d5103f23139f)

2024-02-08 11:38 UTC, antoinebhs approved these changes
Comments above to fix in separate PR

2024-02-08 11:48 UTC, merged