Update CLIENT_COUNT to 9 and add specific client IDs for local devs.
gridsuite/deployment pull request #401
Opened 2024-03-28 14:25 UTC by flomillot

2024-03-28 14:29 UTC, Tristan-WorkGH requested changes
You miss griddyna and gridmerge.

I would keep the same "order" than container like:  
80 -> 3000 (or 3080)  
81 -> 3001 (or 3081)  
etc...

2024-03-28 14:31 UTC, flomillot commented
> You miss griddyna and gridmerge.
> 
> I would keep the same "order" than container like: 80 -> 3000 (or 3080) 81 -> 3001 (or 3081) etc...

Yeah I know I just did the ones I need, and these ones are not used a lot. OK to keep same last digit.

2024-03-28 15:03 UTC, Tristan-WorkGH approved these changes
I've created change for grid-dyna and grid-merge

2024-03-28 17:23 UTC, Tristan-WorkGH approved these changes

2024-03-29 08:28 UTC, EstherDarkish approved these changes

2024-04-02 09:37 UTC, etiennehomer approved these changes

2024-04-02 10:29 UTC, merged