Dashboards postgres & rabbitmq
gridsuite/deployment pull request #403
Opened 2024-04-25 08:38 UTC by SlimaneAmar

2024-04-25 10:19 UTC, Tristan-WorkGH requested changes
1 missing config + 1 question + 1 suggestion

2024-04-25 10:19 UTC, Tristan-WorkGH commented on docker-compose/technical/docker-compose.technical.yml
> +      - DATA_SOURCE_NAME=postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable
in [the documentation](https://github.com/prometheus-community/postgres_exporter#environment-variables), it say
> DATA_SOURCE_NAME the default legacy format. Accepts URI form and key=value form arguments. The URI may contain the username and password to connect with.

Wouldn't it be better not to use legacy parameters even if it's the default?
```suggestion
      DATA_SOURCE_USER: postgres
      DATA_SOURCE_PASS: postgres
      DATA_SOURCE_URI: postgres:5432/postgres?sslmode=disable
```

2024-04-25 11:20 UTC, SlimaneAmar commented on docker-compose/technical/docker-compose.technical.yml
> +      - "9187:9187"
Yes for tests
Only for dev

2024-04-25 11:20 UTC, SlimaneAmar commented on docker-compose/technical/docker-compose.technical.yml
> +
Done

2024-04-26 08:30 UTC, Tristan-WorkGH approved these changes

2024-05-27 14:29 UTC, antoinebhs approved these changes
Code OK
Test OK

I mention here that the JSON dashboards are from:
* https://grafana.com/grafana/dashboards/14191-elasticsearch-overview/,
* https://grafana.com/grafana/dashboards/10991-rabbitmq-overview/, 
* https://grafana.com/grafana/dashboards/9628-postgresql-database/

They will be later extended with alerts.

2024-06-06 07:14 UTC, merged