script to wrap unitary modifications by composite modification
gridsuite/deployment pull request #419
Opened 2024-07-04 06:33 UTC by ghazwarhili

2024-07-04 11:14 UTC, etiennehomer requested changes

2024-07-04 11:14 UTC, etiennehomer commented on migration/migrate_modifications_in_directory_to_composite_modification.sql
> +values ((select id from networkmodifications.composite_modification), 'Generated-modification-composite', 'admin',
Why 'admin' ? The owner should not change

2024-07-04 11:14 UTC, etiennehomer commented on migration/migrate_modifications_in_directory_to_composite_modification.sql
> +        '2024-07-01 21:14:15.517000 +00:00', 'admin', null, false);
Insert with previous date. Or use a function like now()

2024-07-04 11:14 UTC, etiennehomer commented on migration/migrate_modifications_in_directory_to_composite_modification.sql
> +values (new_composite, 'Generated_modification_composite', 'admin',
why admin ? The owner should not change

2024-07-04 11:14 UTC, etiennehomer commented on migration/migrate_modifications_in_directory_to_composite_modification.sql
> +values (new_composite, 'Generated_modification_composite', 'admin',
I think we should keep the previous name. 
Or something like "Composite modification of 'previous name'"

2024-07-04 11:16 UTC, etiennehomer requested changes

2024-07-04 11:16 UTC, etiennehomer commented on migration/migrate_modifications_in_directory_to_composite_modification.sql
> +values (gen_random_uuid(), 'Modification_composite_migration', 'admin',
The script should be as much transparent as possible for users !
Do not create a new create. Modifications should stay in the directory they are

2024-07-04 11:50 UTC, Tristan-WorkGH requested changes
Script not working as is...

2024-07-04 11:50 UTC, Tristan-WorkGH commented on migration/migrate_modifications_in_directory_to_composite_modification.sql
> +        null, 'DIRECTORY', null, '2024-07-02 14:24:50.296498 +00:00', '2024-07-02 14:24:50.296498 +00:00', 'admin', null, false) return id);
```suggestion
        null, 'DIRECTORY', null, now(), now(), 'admin', null, false) return id);
```

2024-07-04 11:50 UTC, Tristan-WorkGH commented on migration/migrate_modifications_in_directory_to_composite_modification.sql
> +        '2024-07-01 21:14:15.517000 +00:00', 'admin', null, false);
```suggestion
        new_directory, 'MODIFICATION', null, now(), now(), 'admin', null, false);
```

2024-07-04 11:50 UTC, Tristan-WorkGH commented on migration/migrate_modifications_in_directory_to_composite_modification.sql
> +commit;
Missing EOL
```suggestion
commit;

```

2024-07-04 11:50 UTC, Tristan-WorkGH commented on migration/migrate_modifications_in_directory_to_composite_modification.sql
> +        null, 'DIRECTORY', null, '2024-07-02 14:24:50.296498 +00:00', '2024-07-02 14:24:50.296498 +00:00', 'admin', null, false) return id);
```suggestion
    new_directory as (insert into directory.element(id, name, owner, parent_id, type, description, creation_date, last_modification_date, last_modified_by, stash_date, stashed)
values (gen_random_uuid(), 'Modification_composite_migration', 'admin', null, 'DIRECTORY', null, now(), now(), 'admin', null, false) returning id)
```

And you're not in the `with` scope here ...  
> <statement> expected, got 'new_directory'
![screenshot](https://github.com/gridsuite/deployment/assets/135599584/db50baf9-6a72-49d8-8a9e-397ef10eb967)

2024-07-05 08:56 UTC, Tristan-WorkGH approved these changes
why so many empty lines?

2024-07-05 09:20 UTC, etiennehomer requested changes

2024-07-05 09:20 UTC, etiennehomer commented on migration/migrate_modifications_in_directory_to_composite_modification.sql
> +    new_composite as (insert into networkmodifications.composite_modification(id) select id from new_modification returning id),
```suggestion
    new_composite_modification_id as (insert into networkmodifications.composite_modification(id) select id from new_modification returning id),
```

2024-07-05 09:20 UTC, etiennehomer commented on migration/migrate_modifications_in_directory_to_composite_modification.sql
> +            returning id, modification_id
```suggestion
            returning id
```

2024-07-05 09:20 UTC, etiennehomer commented on migration/migrate_modifications_in_directory_to_composite_modification.sql
> +            select m.new_id, m.id, row_number() over () as modifications_order from dir_element_with_m_id m
```suggestion
            select m.new_id, m.id, 0 as modifications_order from dir_element_with_m_id m
```

2024-07-05 09:20 UTC, etiennehomer commented on migration/migrate_modifications_in_directory_to_composite_modification.sql
> +    dir_element_with_m_id as (select *, gen_random_uuid() as new_id from directory.element where type = 'MODIFICATION'),
Can't we only work with this common table expression and avoid all the other "as".
Actually, we only need to work with oldId and newId, they don't change

2024-07-05 09:20 UTC, etiennehomer commented on migration/migrate_modifications_in_directory_to_composite_modification.sql
> +    new_element_modification as (
new_element_modification_id

2024-07-08 09:34 UTC, etiennehomer requested changes

2024-07-08 09:34 UTC, etiennehomer commented on migration/migrate_modifications_in_directory_to_composite_modification_fix.sql
> +update networkmodifications.public.modification e
```suggestion
update networkmodifications.modification e
```

2024-07-08 09:40 UTC, etiennehomer requested changes

2024-07-08 09:40 UTC, etiennehomer commented on migration/migrate_modifications_in_directory_to_composite_modification.sql
> +    (select new_id, id, 0 from MODIFICATION_ELEMENTS);
Add : 
drop table MODIFICATION_ELEMENTS;

2024-07-08 09:40 UTC, etiennehomer commented on migration/migrate_modifications_in_directory_to_composite_modification_fix.sql
> +set date = CURRENT_DATE,
```suggestion
set date = (select creation_date from modification_elements where id = e.id) ,
```

2024-07-08 09:40 UTC, etiennehomer commented on migration/migrate_modifications_in_directory_to_composite_modification_fix.sql
> +  AND message_values IS NULL;
add : 
drop table MODIFICATION_ELEMENTS;

2024-07-08 12:43 UTC, etiennehomer approved these changes

2024-07-08 12:46 UTC, etiennehomer approved these changes

2024-07-08 12:54 UTC, merged