Add spreadsheet config server
gridsuite/deployment pull request #432
Opened 2024-09-27 08:45 UTC by achour94

2024-09-27 12:10 UTC, TheMaskedTurtle requested changes

2024-09-27 12:10 UTC, TheMaskedTurtle commented on k8s/resources/common/spreadsheet-config-server-deployment.yaml
> +    gridsuite.org/size: springboot-m
You can put xxs for now, we'll see later on if it needs more resources

2024-09-30 07:19 UTC, FranckLecuyer approved these changes

2024-10-01 07:08 UTC, AbdelHedhili approved these changes

2024-10-01 14:40 UTC, TheMaskedTurtle approved these changes

2024-10-01 17:46 UTC, merged