replace computation counts with density metrics
gridsuite/deployment pull request #446
Opened 2024-10-31 13:15 UTC by jamal-khey

2024-11-05 09:34 UTC, antoinebhs requested changes
When there are two pods it displays the two pods instead of aggregating:
![image](https://github.com/user-attachments/assets/13b31a59-563f-4c15-9032-2e882dac8945)
For short circuit the display is strange:
![Sans titreqdz](https://github.com/user-attachments/assets/8cc1779f-0213-4248-9198-e6acc58a9a25)

The title of the visualization is also misleading because it says "Computation Density (successful computations/min)" while from my understanding it's computations/rate_interval?

2024-11-14 13:19 UTC, antoinebhs commented on docker-compose/technical/grafana/dashboards/computations_metrics.json
> +          "expr": "sum(rate(app_computation_count_total{type='$COMPUTATION', status='OK'}[$__rate_interval])) by (provider) * 60",
```suggestion
          "expr": "sum(rate(app_computation_count_total{type='$COMPUTATION', status='NOK'}[$__rate_interval])) by (provider) * 60",
```
?

2024-11-14 13:36 UTC, SlimaneAmar commented on docker-compose/technical/grafana/dashboards/computations_metrics.json
> +          "expr": "sum(rate(app_computation_count_total{type='$COMPUTATION', status='OK'}[$__rate_interval])) by (provider) * 60",
Done

2024-11-14 13:38 UTC, antoinebhs approved these changes

2024-11-14 14:52 UTC, merged